import { useNavigate } from 'react-router-dom'
import assetChart from './images/assetChart.png'
import medianAssetValuesChart from './images/medianAssetValuesChart.png'
import successChart from './images/successChart.png'
import './Landing.css'

const Landing = () => {

  const navigate = useNavigate()

  return (
    <>
      <div id="landing-page">
        <div id="landing-page-header">
          <div id="landing-page-header-content">
            <h3>Life Financial Planner</h3>
            <button id="landing-page-login-button" onClick={() => navigate("/login")}>
              Login or Sign Up
            </button>
          </div>
        </div>
        <div id="title-section">
          <h1>Life Financial Planner</h1>
          <h2>Plan your financial future today.</h2>
          <button className="landing-page-button" onClick={() => navigate("/login")}>Start Planning</button> 
        </div>
        <div id="about-section">
          <h2>What is Life Financial Planner?</h2>
          <p>
            Life Financial Planner (LFP) helps you project how your financial decisions today may shape your future. By inputting your current finances and long-term goals, LFP simulates real-world economic factors such as inflation, asset growth, and market performance to forecast your financial trajectory throughout your lifetime.
          </p>
          <div id="chart-examples-section">
            <img id="asset-chart-example" className='chart-example' src={assetChart}/>
            <img id="success-chart-example" className='chart-example' src={successChart}/>
            <img id="median-asset-chart-example" className='chart-example' src={medianAssetValuesChart}/>
          </div>
        </div>
        <div id="footer">
          <p id="disclaimer"><span>Disclaimer: </span>The information provided by Life Financial Planner is for informational and educational purposes only, and is not professional financial or investment advice. The results generated by Life Financial Planner is not guaranteed to be accurate or complete. Consult with a financial services professional before making any significant investments or financial decisions.</p>
        </div>
      </div>
    </>
  )
}

export default Landing